apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-e4fw
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0061-tenant/tkrw-pr712-0075-0061-app/devfile-sample-e4fw@sha256:646472e4f4cec717107a620f5653edcfbdc9c0ed474481fa09655780745498cb
        name: my-nodejs
        resources: {}
status: {}
