apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-e4fw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-e4fw
    app.kubernetes.io/part-of: tkrw-pr712-0075-0061-app
  name: devfile-sample-e4fw
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-e4fw
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-e4fw
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0061-tenant/tkrw-pr712-0075-0061-app/devfile-sample-e4fw@sha256:646472e4f4cec717107a620f5653edcfbdc9c0ed474481fa09655780745498cb
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
